# This is a generated file. Not intended for manual editing.
services:
  ptixiakireservations:
    build:
      context: "D:\\Rider Projects\\PtixiakiReservations"
      dockerfile: "PtixiakiReservations/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/PtixiakiReservations.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/PtixiakiReservations.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ptixiakireservations:dev"
    ports: []
    volumes:
    - "D:\\Rider Projects\\PtixiakiReservations\\PtixiakiReservations:/app:rw"
    - "D:\\Rider Projects\\PtixiakiReservations:/src:rw"
    - "C:\\Users\\nikos\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
