# This is a generated file. Not intended for manual editing.
services:
  ptixiakireservations:
    build:
      context: "/Users/nickantoniadis/Documents/Repositories/PtixiakiReservations"
      dockerfile: "PtixiakiReservations/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/PtixiakiReservations.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/PtixiakiReservations.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ptixiakireservations:dev"
    ports: []
    volumes:
    - "/Users/nickantoniadis/Documents/Repositories/PtixiakiReservations/PtixiakiReservations:/app:rw"
    - "/Users/nickantoniadis/Documents/Repositories/PtixiakiReservations:/src:rw"
    - "/Users/nickantoniadis/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
