services:
  ptixiakireservations:
    image: ptixiakireservations
    build:
      context: .
      dockerfile: PtixiakiReservations/Dockerfile
    volumes:
      # Dynamic approach using environment variables with fallbacks
      - ${NUGET_PACKAGES_PATH:-${HOME:-.}/.nuget/packages}:/home/app/.nuget/packages:ro
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.4.246;Database=ReservationProject;User Id=sa;Password=Blaze2310;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__PostgresConnection=Host=postgres;Database=ReservationProject;Username=postgres;Password=Blaze2310
      - ElasticSettings__Uri=http://${ES_HOST:-elasticsearch}:9200
    depends_on:
      - postgres
    networks:
      - reservations
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=ReservationProject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Blaze2310
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - reservations

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - reservations

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - reservations

networks:
  reservations:
    driver: bridge

volumes:
  elasticsearch-data:
  postgres-data: